// Builds `firestore.rules` from `rules/firestore/` (foundation ADR-0012) and
// `storage.rules` from `rules/storage/` (foundation ADR-0013). The files
// Firebase deploys and the emulator loads are generated and committed; the
// partials are what people edit.
//
//   node tools/build-rules.mjs           write both files
//   node tools/build-rules.mjs --check   exit 1 if either is out of date
//
// Why: one rules file every feature edits went past the 500-line cap (`ENG-05`)
// and was the one conflict every parallel branch hit. A feature now owns its
// own partial, and adding one is a new file nobody else touches.
//
// Layout — each directory is a scope, each file is one feature's block, files
// are read in name order, and the builder supplies the indentation:
//
//   rules/firestore/shared/*.rules     functions every match may call
//   rules/firestore/root/*.rules       top-level `match /<collection>/{id}` blocks
//   rules/firestore/household/*.rules  blocks inside `match /households/{householdId}`
//   rules/storage/shared/*.rules       functions every Storage match may call
//   rules/storage/paths/*.rules        `match /<full object path>` blocks in the bucket
//
// Order does not change what the rules mean: functions are visible to their
// whole scope, and a request is allowed when any matching rule allows it.

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..');

const FIRESTORE_HEAD = `rules_version = '2';

// GENERATED by \`npm --prefix functions run rules:build\` from rules/firestore/.
// Do not edit this file: edit the partial named above each block, then build.
// A merge conflict here is never resolved by hand — take either side and build.
//
// NestPrep's authorisation and validation layer (foundation ADR-0002). Deny by
// default; every match states who may read and who may write, and every rule has
// an allowed and a denied test in \`functions/test/rules/\` (BE-05, BE-14).
//
// Membership is read from the household document's uid→role map, which only
// Cloud Functions write. Everything a household owns is nested under it, so the
// scope is structural rather than repeated per collection.
service cloud.firestore {
  match /databases/{database}/documents {
`;

const FIRESTORE_HOUSEHOLD_OPEN = `
    // ---- households (household ADR-0001, ADR-0002) ----

    match /households/{householdId} {
`;

const FIRESTORE_TAIL = `
    // Everything not named above (BE-05).
    match /{document=**} {
      allow read, write: if false;
    }
  }
}
`;

const STORAGE_HEAD = `rules_version = '2';

// GENERATED by \`npm --prefix functions run rules:build\` from rules/storage/.
// Do not edit this file: edit the partial named above each block, then build.
// A merge conflict here is never resolved by hand — take either side and build.
//
// NestPrep's authorisation layer for the bytes a household keeps (documents
// ADR-0001). Same posture as \`firestore.rules\`: deny by default, every match
// states who may read and who may write, and every rule has an allowed and a
// denied test in \`functions/test/rules/\` (BE-05, BE-14).
//
// The difference that shapes this whole file: **Storage rules cannot read
// Firestore the cheap way.** The uid→role map every Firestore rule consults
// arrives here as a custom claim on the caller's ID token —
// \`households: { householdId: role }\` plus \`access\` for per-area grants —
// which the Functions write from what Firestore already says. A claim is up to
// an hour stale after a removal; a path that must refuse at once (the vaults,
// home care's job photos) pays for a live cross-service \`firestore.get()\`.
service firebase.storage {
  match /b/{bucket}/o {
`;

const STORAGE_TAIL = `
    // Everything not named above (BE-05).
    match /{allPaths=**} {
      allow read, write: if false;
    }
  }
}
`;

/** Every partial in one scope, in name order, as `{ path, source }`. */
function partialsIn(tree, scope) {
  const dir = join(repoRoot, 'rules', tree, scope);
  return readdirSync(dir)
    .filter((name) => name.endsWith('.rules'))
    .sort()
    .map((name) => ({
      path: `rules/${tree}/${scope}/${name}`,
      source: readFileSync(join(dir, name), 'utf8'),
    }));
}

function indented(source, depth) {
  const pad = ' '.repeat(depth);
  return source
    .replace(/\s+$/, '')
    .split('\n')
    .map((line) => (line.trim() === '' ? '' : pad + line))
    .join('\n');
}

function scopeBlock(tree, scope, depth) {
  return partialsIn(tree, scope)
    .map(
      ({ path, source }) => `${' '.repeat(depth)}// ==== ${path} ====\n${indented(source, depth)}`,
    )
    .join('\n\n');
}

export function buildFirestoreRules() {
  return [
    FIRESTORE_HEAD,
    scopeBlock('firestore', 'shared', 4),
    '\n\n',
    scopeBlock('firestore', 'root', 4),
    '\n',
    FIRESTORE_HOUSEHOLD_OPEN,
    scopeBlock('firestore', 'household', 6),
    '\n    }\n',
    FIRESTORE_TAIL,
  ].join('');
}

export function buildStorageRules() {
  return [
    STORAGE_HEAD,
    scopeBlock('storage', 'shared', 4),
    '\n\n',
    scopeBlock('storage', 'paths', 4),
    '\n',
    STORAGE_TAIL,
  ].join('');
}

/** What each generated file is built from, for the builder and its test. */
export const GENERATED = [
  {
    file: 'firestore.rules',
    tree: 'firestore',
    scopes: ['shared', 'root', 'household'],
    build: buildFirestoreRules,
  },
  { file: 'storage.rules', tree: 'storage', build: buildStorageRules },
];

const isMain =
  process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const check = process.argv.includes('--check');
  let stale = false;
  for (const { file, tree, build } of GENERATED) {
    const outputPath = join(repoRoot, file);
    const built = build();
    if (check) {
      if (readFileSync(outputPath, 'utf8') !== built) {
        console.error(
          `${file} is out of date with rules/${tree}/. Run \`npm --prefix functions run rules:build\` and commit it.`,
        );
        stale = true;
      } else {
        console.log(`${file} is up to date.`);
      }
    } else {
      writeFileSync(outputPath, built);
      console.log(`Wrote ${file} (${built.split('\n').length - 1} lines).`);
    }
  }
  if (stale) process.exit(1);
}
