// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA51y17wxHN1wcmXwzkMf1p8yDxggI3O1Y',
    appId: '1:388847987716:android:3c7b01370726812f7c5951',
    messagingSenderId: '388847987716',
    projectId: 'nestprep-643b7',
    storageBucket: 'nestprep-643b7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHTJQGg7UN4rC2p3aypOD0Wiv5rcvXYDk',
    appId: '1:388847987716:ios:38fce2c74d9cd9427c5951',
    messagingSenderId: '388847987716',
    projectId: 'nestprep-643b7',
    storageBucket: 'nestprep-643b7.firebasestorage.app',
    androidClientId: '388847987716-2p4eaga9c540g16l2i8i7fsv85c839af.apps.googleusercontent.com',
    iosClientId: '388847987716-krbsuibgidj259tpf7o0i24gg2uvo56o.apps.googleusercontent.com',
    iosBundleId: 'io.nullstate.nestprep',
  );
}
